# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71af53a70be8a6fd6fa3ebb315cf5352dbed06828865d7170290f10d4e94297ff0c4f28ab842bb14f310dcb0072ceff26d37c6f12e558463f91e119687ca2b48

test:
  secret_key_base: 7abc8b4afdff8f4be87175572e0ac0a50a4c08d8b32ec9004862c26f58234181e44120eaa38ae87c39d1b2709e56b93fc588b281a1f2e3f29175fbb91c32d061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 20b43b418176ba6d101470fecff4a2ab61e01a39a28dc99e4411bc3e5f017e89ee549022fafe51a94bce1ba002ef518fa51ff0fea62b217bdf41983355bf904a
